apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ghcr.io/oleksandrtimoshenko/nginx-app
        ports:
        - containerPort: 80
        #imagePullPolicy: Never # using local docker images
        imagePullPolicy: Always
      imagePullSecrets:
      - name: hub-info
