apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  type: LoadBalancer
  selector:
    app: postgresql
  ports:
  - port: 5432        # external port
    targetPort: 5432  # port in container
